/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SBackdrop {}
  interface SBackdropAttributes extends StencilHTMLAttributes {}

  interface SModal {
    'mtitle': string;
    'open': () => void;
  }
  interface SModalAttributes extends StencilHTMLAttributes {
    'mtitle'?: string;
  }

  interface SSideDrawer {
    'open': boolean;
    'title': string;
  }
  interface SSideDrawerAttributes extends StencilHTMLAttributes {
    'open'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SBackdrop': Components.SBackdrop;
    'SModal': Components.SModal;
    'SSideDrawer': Components.SSideDrawer;
  }

  interface StencilIntrinsicElements {
    's-backdrop': Components.SBackdropAttributes;
    's-modal': Components.SModalAttributes;
    's-side-drawer': Components.SSideDrawerAttributes;
  }


  interface HTMLSBackdropElement extends Components.SBackdrop, HTMLStencilElement {}
  var HTMLSBackdropElement: {
    prototype: HTMLSBackdropElement;
    new (): HTMLSBackdropElement;
  };

  interface HTMLSModalElement extends Components.SModal, HTMLStencilElement {}
  var HTMLSModalElement: {
    prototype: HTMLSModalElement;
    new (): HTMLSModalElement;
  };

  interface HTMLSSideDrawerElement extends Components.SSideDrawer, HTMLStencilElement {}
  var HTMLSSideDrawerElement: {
    prototype: HTMLSSideDrawerElement;
    new (): HTMLSSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    's-backdrop': HTMLSBackdropElement
    's-modal': HTMLSModalElement
    's-side-drawer': HTMLSSideDrawerElement
  }

  interface ElementTagNameMap {
    's-backdrop': HTMLSBackdropElement;
    's-modal': HTMLSModalElement;
    's-side-drawer': HTMLSSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
