/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SBackdrop {}
  interface SBackdropAttributes extends StencilHTMLAttributes {}

  interface SModal {}
  interface SModalAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'SBackdrop': Components.SBackdrop;
    'SModal': Components.SModal;
  }

  interface StencilIntrinsicElements {
    's-backdrop': Components.SBackdropAttributes;
    's-modal': Components.SModalAttributes;
  }


  interface HTMLSBackdropElement extends Components.SBackdrop, HTMLStencilElement {}
  var HTMLSBackdropElement: {
    prototype: HTMLSBackdropElement;
    new (): HTMLSBackdropElement;
  };

  interface HTMLSModalElement extends Components.SModal, HTMLStencilElement {}
  var HTMLSModalElement: {
    prototype: HTMLSModalElement;
    new (): HTMLSModalElement;
  };

  interface HTMLElementTagNameMap {
    's-backdrop': HTMLSBackdropElement
    's-modal': HTMLSModalElement
  }

  interface ElementTagNameMap {
    's-backdrop': HTMLSBackdropElement;
    's-modal': HTMLSModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
